# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d5b3eef247834793168b37543eebfb66de969aa73203eaf14feab85fa6addc19b51d9155ff80337b2d991e1a43287578de9786e1e42fd613e706d31041ec2b7

test:
  secret_key_base: 6402c76a05e5e34936b1eec636696433337a864d631a5285f49033fcbb612ad8c350a510daa7e41fb7835c88ec372e669f3d3a47311524531ea92b601112c5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
